name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake --build /home/gal/dev/Scheduler/build --config Debug --target all --
    - name: make
      run: ctest -j14 -C Debug -T test --output-on-failure
